name: Metrics
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Fetch external contributed repos
        id: auto-discover
        env:
          GH_TOKEN: ${{ secrets.METRICS_TOKEN }}
        run: |
          discovered_repos=$(gh search prs --author Meehir5907 --merged --json repository --jq '[.[].repository.nameWithOwner | select(. | startswith("Meehir5907/") | not)] | unique | join(", ")')
          echo "repos=$discovered_repos" >> $GITHUB_OUTPUT

      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics.svg
          base: header, activity, community, repositories, metadata
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: bytes-size, percentage
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_notable: yes
          plugin_notable_from: all
          plugin_languages_sections: most-used, recently-used
          plugin_languages_recent_days: 90
          plugin_languages_recent_load: 1500
          plugin_languages_indepth: yes
          plugin_languages_indepth_custom: ${{ steps.auto-discover.outputs.repos }}
          commits_authoring: Meehir Prabhakar, Meehir5907
